services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: web.localhost
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/web:ro
    environment:
      VIRTUAL_HOST: web.localhost
  iglu:
    image: nginx:alpine
    container_name: iglu
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/web:ro
  micro:
    image: snowplow/snowplow-micro
    ports:
      - "9090:9090"
    environment:
      VIRTUAL_HOST: micro.localhost